from pathlib import Path
import json
from html import escape
ROOT=Path(__file__).resolve().parents[1]
BASE='https://joshthetechtamer.com'
icons={
'home':'<path d="M3 11 12 3l9 8v10h-6v-7H9v7H3z"/>',
'business':'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12c5 4 13 4 18 0M10 13h4"/>',
'book':'<path d="M12 5c-4-3-8-2-10-1v16c3-2 7-2 10 0 3-2 7-2 10 0V4c-2-1-6-2-10 1v15"/>',
'pc':'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4M6 7h7"/>',
'phone':'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 5h4M11 19h2"/>',
'wifi':'<path d="M2 8a16 16 0 0 1 20 0M5 12a11 11 0 0 1 14 0M8 16a6 6 0 0 1 8 0"/><circle cx="12" cy="20" r="1"/>',
'tv':'<rect x="2" y="6" width="20" height="14" rx="2"/><path d="m8 2 4 4 4-4m-6 9 5 3-5 3z"/>',
'shield':'<path d="m12 2 9 4v6c0 5-6 9-9 10-3-1-9-5-9-10V6zM8 12l3 3 5-6"/>',
'camera':'<rect x="2" y="7" width="14" height="12" rx="2"/><path d="m16 11 6-4v12l-6-4M6 4h6"/>',
'pen':'<path d="m4 16 12-12 4 4L8 20l-5 1zM13 7l4 4M4 16l4 4"/>',
'ad':'<path d="m3 9 17-6v17L3 14zM6 15l2 7h4l-2-6M20 9h3M20 14h3"/>',
'rocket':'<path d="M8 16C7 8 13 3 21 3c0 8-5 14-13 13zM8 11H4l-2 6 6-1m5 0v4l-6 2 1-6M5 19l-3 3"/><circle cx="16" cy="8" r="2"/>',
'web':'<rect x="2" y="3" width="20" height="18" rx="2"/><path d="M2 8h20M6 5h1M10 5h1M7 12l-3 3 3 3m10-6 3 3-3 3m-4-7-2 9"/>'}
def icon(name):return '<div class="icon" aria-hidden="true"><svg viewBox="0 0 24 24">'+icons[name]+'</svg></div>'
def btn(text,href='contact.html',kind=''):return f'<a class="btn {kind}" href="{href}">{text}<span aria-hidden="true">↗</span></a>'
def link(text,href):return f'<a class="textlink" href="{href}">{text}</a>'
def eyebrow(text):return f'<div class="eyebrow">{text}</div>'
def checks(items):return '<ul class="checklist">'+''.join(f'<li>{i}</li>' for i in items)+'</ul>'
navitems=[('services.html','Tech Help'),('business.html','For Business'),('digital-kits.html','Digital Kits'),('rates.html','Rates & FAQ'),('about.html','About Josh')]
def header(page):
 return '''<a href="#main" class="skip">Skip to content</a><div class="topline"><div class="wrap"><span>Muscatine based. Proudly serving Eastern Iowa.</span><a class="right" href="tel:+15632610200">Let’s talk: 563-261-0200</a></div></div><header class="site-header"><div class="wrap nav-row"><a href="index.html" class="brand" aria-label="The Tech Tamer home"><img src="assets/logo.png" alt="" width="58" height="58"><div><strong>THE TECH TAMER</strong><span>Technology. Tamed.</span></div></a><button class="menu" aria-controls="navigation" aria-expanded="false" type="button">Menu ☰</button><nav class="navlinks" id="navigation" aria-label="Main navigation">'''+''.join(f'<a href="{url}"'+(' aria-current="page"' if url==page else '')+f'>{label}</a>' for url,label in navitems)+f'<a class="nav-contact" href="contact.html"'+(' aria-current="page"' if page=='contact.html' else '')+'>Let’s talk ↗</a></nav></div></header>'
def cta(title='Let’s get your technology working.',sub='Start with a free consultation. Tell Josh what you need help with.'):
 return '<section class="cta"><div class="wrap"><div><h2>'+title+'</h2><p>'+sub+'</p></div><div class="actions">'+btn('Text Josh','sms:+15632610200','light')+btn('Call Josh','tel:+15632610200','outline-light')+'</div></div></section>'
def footer():
 return '''<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a href="index.html" class="brand"><div><strong>THE TECH TAMER</strong><span>Technology. Tamed.</span></div></a><p>Friendly tech help and practical business solutions, with Josh Sargent.</p><p>Muscatine · Iowa City · Quad Cities</p></div><div><h3>Explore</h3><a href="services.html">Tech help at home</a><a href="business.html">Small-business solutions</a><a href="digital-kits.html">Digital kits</a><a href="rates.html">Rates & FAQ</a><a href="about.html">Meet Josh</a></div><div><h3>Get in touch</h3><a href="tel:+15632610200">563-261-0200</a><a href="contact.html">Free consultation</a><a href="https://www.facebook.com/profile.php?id=61575951953109" target="_blank" rel="noopener noreferrer">Facebook ↗</a><a href="https://www.linkedin.com/in/josh-sargent-adsales" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div><div><h3>Availability</h3><p>Sun–Tue & Thu–Sat<br>8 AM–8 PM</p><p>Wednesday: appointment setting only.<br>Contact Josh to arrange a visit.</p></div></div><div class="footer-bottom"><span>© 2026 The Tech Tamer LLC. All rights reserved.</span><span>Real help. Plain English. Eastern Iowa.</span></div></div></footer><div class="mobile-contact" aria-label="Quick contact"><a class="btn" href="sms:+15632610200">Text Josh</a><a class="btn secondary" href="tel:+15632610200">Call 563-261-0200</a></div>'''
def pagehero(label,title,desc):
 return '<section class="page-hero dots"><div class="wrap"><div class="breadcrumb"><a href="index.html">Home</a><span>/</span>'+label+'</div>'+eyebrow(label)+'<h1>'+title+'</h1><p class="lead">'+desc+'</p></div></section>'
def with_help_photo(section, hero=False):
 photo = '<div class="help-photo"><img src="assets/josh-helping.jpg" alt="Josh smiling and helping a woman with her laptop at a kitchen table" width="1536" height="1152" fetchpriority="high"></div>'
 if hero:
  section = section.replace('page-hero dots', 'page-hero dots tech-help-hero').replace('<div class="wrap">', '<div class="wrap help-hero-grid"><div class="help-hero-copy">', 1)
  return section.removesuffix('</div></section>') + '</div>' + photo + '</div></section>'
 photo = photo.replace('fetchpriority="high"', 'loading="lazy"')
 section = section.replace('class="cta"', 'class="cta cta-photo"', 1).replace('<div class="wrap">', '<div class="wrap">' + photo + '<div class="help-cta-copy">', 1)
 return section.removesuffix('</div></section>') + '</div></div></section>'
def with_business_photo(section):
 section = section.replace('page-hero dots', 'page-hero dots tech-help-hero').replace('<div class="wrap">', '<div class="wrap help-hero-grid"><div class="help-hero-copy">', 1)
 return section.removesuffix('</div></section>') + '</div>' + '<div class="help-photo"><img src="assets/josh-business.jpg" alt="Josh Sargent holding a laptop and wearing his Tech Tamer polo" width="1534" height="1536" fetchpriority="high"></div>' + '</div></section>'
def with_kits_illustration(section):
 section = section.replace('page-hero dots', 'page-hero dots tech-help-hero').replace('<div class="wrap">', '<div class="wrap help-hero-grid"><div class="help-hero-copy">', 1)
 return section.removesuffix('</div></section>') + '</div>' + '<div class="help-photo"><img src="assets/kits-hero.webp" alt="The Tech Tamer mascot following an illustrated kit to set up a Wi-Fi router" width="1536" height="1024" fetchpriority="high"></div>' + '</div></section>'
def with_rates_illustration(section):
 section = section.replace('page-hero dots', 'page-hero dots tech-help-hero').replace('<div class="wrap">', '<div class="wrap help-hero-grid"><div class="help-hero-copy">', 1)
 return section.removesuffix('</div></section>') + '</div>' + '<div class="help-photo"><img src="assets/rates-hero.png" alt="The Tech Tamer tipping his hat as payment drops in—straightforward rates for straightforward help" width="1536" height="1024" fetchpriority="high"></div>' + '</div></section>'
def with_rates_cta_photo(section):
 photo = '<div class="help-photo"><img src="assets/rates-cta-shrug.png" alt="The Tech Tamer shrugging with a question mark—start with a conversation about what’s going on" width="1536" height="1024" loading="lazy"></div>'
 section = section.replace('class="cta"', 'class="cta cta-photo"', 1).replace('<div class="wrap">', '<div class="wrap">' + photo + '<div class="help-cta-copy">', 1)
 return section.removesuffix('</div></section>') + '</div></div></section>'

def with_tech_help_cta_photo(section):
 photo = '<div class="help-photo"><img src="assets/tech-help-cta-headache.png" alt="The Tech Tamer tangled in cables and devices—let’s tackle that tech headache together" width="1536" height="1024" loading="lazy"></div>'
 section = section.replace('class="cta"', 'class="cta cta-photo"', 1).replace('<div class="wrap">', '<div class="wrap">' + photo + '<div class="help-cta-copy">', 1)
 return section.removesuffix('</div></section>') + '</div></div></section>'

def with_business_cta_photo(section):
 photo = '<div class="help-photo"><img src="assets/business-cta-working.png" alt="The Tech Tamer at a desk with charts and a laptop—what are you working on?" width="1536" height="1024" loading="lazy"></div>'
 section = section.replace('class="cta"', 'class="cta cta-photo"', 1).replace('<div class="wrap">', '<div class="wrap">' + photo + '<div class="help-cta-copy">', 1)
 return section.removesuffix('</div></section>') + '</div></div></section>'

def document(filename,title,desc,body):
 schema={'@context':'https://schema.org','@type':'LocalBusiness','name':'The Tech Tamer LLC','url':BASE,'telephone':'+15632610200','email':'joshthetechtamer@gmail.com','image':BASE+'/assets/logo.png','priceRange':'$50/hour','areaServed':['Muscatine','Iowa City','Quad Cities'],'address':{'@type':'PostalAddress','addressLocality':'Muscatine','addressRegion':'IA','postalCode':'52761','addressCountry':'US'},'sameAs':['https://www.facebook.com/profile.php?id=61575951953109']}
 url=BASE+'/' + (filename if filename!='index.html' else '')
 text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | The Tech Tamer</title><meta name="description" content="{escape(desc,quote=True)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{escape(title,quote=True)} | The Tech Tamer"><meta property="og:description" content="{escape(desc,quote=True)}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><meta property="og:image" content="https://static.readdy.ai/image/2b86c33b7e31113c8376c50d779cc539/c4f6cd71f4bf8a31e37ed5d24fad2151.png"><link rel="icon" href="/assets/logo.png?v=20261001" type="image/png"><link rel="apple-touch-icon" href="/assets/logo.png?v=20261001"><link rel="stylesheet" href="assets/site.css"><script type="application/ld+json">{json.dumps(schema)}</script><script src="assets/site.js" defer></script></head><body>{header(filename)}<main id="main">{body}</main>{footer()}</body></html>'''
 (ROOT/filename).write_text(text)

home='''<section class="hero"><div class="wrap hero-grid"><div class="hero-copy">'''+eyebrow('Your local tech guy · Muscatine, Iowa')+'''<h1>Less tech trouble.<br><span>More life.</span></h1><p class="lead">From the Wi-Fi that won’t cooperate to the business you’re ready to launch. I’m Josh, and I’ll help you get it working.</p><div class="actions">'''+btn('Text Josh','sms:+15632610200')+btn('Explore services','services.html','secondary')+'''</div><div class="hero-facts"><div><b>Free consultation</b>Let’s talk it through.</div><div><b>Local, personal help</b>Work directly with Josh.</div></div></div><div class="hero-art"><img src="assets/logo.png" width="1080" height="1080" alt="The Tech Tamer: Josh’s top-hatted technology tamer mascot"><div class="art-label">A familiar face. A helping hand.</div></div></div></section><div class="ribbon"><div class="wrap ribbon-inner"><div><strong>$50 <small>/ hour</small></strong></div><p>Free consultation. Estimates for larger projects.</p>'''+link('View rates','rates.html')+'''</div></div><section class="section"><div class="wrap"><div class="section-head"><div>'''+eyebrow('What can I help you tame?')+'''<h2>A little help goes a long way.</h2></div><p>Pick your starting point. We’ll figure out the next step together.</p></div><div class="grid3">'''
paths=[('home','01','Tech help at home','Printers, phones, Wi-Fi, TVs, and all the things that should make life easier.',['Setup','Troubleshooting','Patient guidance'],'Find your tech fix','services.html'),('business','02','A boost for your business','Bring your idea to life with branding, advertising setup, and practical startup guidance.',['Logo & brand','Ad setup','Startup support'],'Build your next chapter','business.html'),('book','03','Do it yourself, confidently','Plain-English guides and checklists for a more secure home network or small business.',['Instant downloads','Step-by-step guides'],'Browse digital kits','digital-kits.html')]
for ic,n,title,desc,tags,lt,url in paths:
 home+=f'<article class="path-card">{icon(ic)}<span class="card-number">{n}</span><h3>{title}</h3><p>{desc}</p><div class="tags">'+''.join(f'<span class="tag">{t}</span>' for t in tags)+f'</div>{link(lt,url)}</article>'
home+='''</div></div></section><section class="section tint"><div class="wrap"><div class="section-head"><div>'''+eyebrow('No jargon. No runaround.')+'''<h2>Getting help should be easy.</h2></div></div><div class="grid3">'''
for n,t,d in [('01','Tell me what’s going on.','Send a text or give me a call. A quick conversation helps us figure out what you need.'),('02','Know the plan and the price.','Tech help is $50/hour. Larger projects start with a free consultation and an estimate.'),('03','Let’s get it handled.','We’ll arrange the next step, work through the problem, and make sure you’re comfortable using it.')]:home+=f'<div class="step"><div class="number">{n}</div><h3>{t}</h3><p>{d}</p></div>'
home+='''</div></div></section><section class="section"><div class="wrap"><div class="about-tease"><div class="portrait"><img src="assets/josh.jpg" loading="lazy" width="600" height="600" alt="Josh Sargent, The Tech Tamer"></div><div>'''+eyebrow('Meet the guy behind the top hat')+'''<h2>Howdy, I’m Josh.</h2><p>I’m the person you call when your technology has other plans. I help neighbors and small businesses across Eastern Iowa solve problems, set things up, and feel more confident using their tech.</p><p>Need someone who can explain it without making you feel silly for asking? You’re in the right place.</p>'''+link('A little more about me','about.html')+'''<div class="credentials" style="margin-top:26px"><span>Electronics engineering graduate</span><span>Network engineering training</span></div></div></div></div></section>'''+cta()
document('index.html','Tech Help & Small-Business Solutions in Muscatine','Friendly local tech support, branding, advertising setup, and startup guidance in Eastern Iowa. $50/hour with a free consultation.',home)

services=with_help_photo(pagehero('Tech help','Your technology.<br>Working for you.','A new device to set up. An old problem to finally solve. Patient, practical help for your home and everyday technology.'), hero=True)+'<section class="section"><div class="wrap"><div class="grid3">'
service_data=[('pc','computers','Computers & printers','Get back to using your computer instead of fighting with it.',['Windows and Mac setup','Printer and connection problems','Software troubleshooting','New-computer setup and file transfers']),('phone','phones','Phones & tablets','Make your device work the way you want it to.',['New-device setup','Email, apps, and settings','Photos, contacts, and backups','One-on-one device guidance']),('wifi','wifi','Wi-Fi & home networks','Help your internet reach the places you actually use it.',['Router and Wi-Fi setup','Connection troubleshooting','Coverage and device connections','Home-network security settings']),('tv','entertainment','TVs & streaming','Spend less time switching inputs and more time watching.',['Smart TV and streaming setup','Home theater and sound systems','Remote-control guidance','Connected-device setup']),('camera','smart-home','Smart devices & cameras','Bring your connected devices together with less guesswork.',['Smart-home device setup','Compatible camera app setup','Notifications and remote viewing','Device selection and planning']),('shield','accounts','Accounts & scam help','A calm helping hand when something looks suspicious.',['Account recovery guidance','Password and sign-in protection','Scam awareness and prevention','Unwanted pop-up troubleshooting'])]
for ic,id,t,d,items in service_data:services+=f'<article class="service-card" id="{id}">{icon(ic)}<h2>{t}</h2><p>{d}</p>{checks(items)}{link("Ask Josh about this","contact.html")}</article>'
services+='</div><div class="notice"><strong>Don’t see your exact problem?</strong> Tell me what’s going on. I’ll help you figure out whether it’s something I can handle and what the next step should be. Camera and smart-device projects start with a conversation about the equipment and setup needed.</div></div></section>'+with_tech_help_cta_photo(cta('Let’s tackle that tech headache.','Free consultation · $50/hour · Serving Muscatine, Iowa City & the Quad Cities'))
document('services.html','Computer, Wi-Fi, Phone & TV Help','Local help with computers, printers, Wi-Fi, phones, TVs, smart devices, and account security in Muscatine and Eastern Iowa.',services)

business=with_business_photo(pagehero('For business','Your big idea.<br>Let’s make it work.','Logo and brand work, advertising setup, and practical startup consulting for small businesses ready to get moving.'))+'<section class="section"><div class="wrap"><div class="business-intro"><div>'+eyebrow('From first idea to next step')+'<h2>One person to help connect the pieces.</h2><p class="lead">Starting a business means a lot of decisions. Your logo, your online presence, the way you reach customers, and the tools you use every day should work together.</p><p>I’ll help you sort out what matters now, choose a practical next step, and turn the plan into something you can use.</p>'+link('Talk through your project','contact.html')+'</div><aside class="business-panel"><h2>A clear starting point.</h2><p>Every project begins with a free conversation about your business, your goals, and what you already have.</p><ol><li>Define what you need.</li><li>Agree on the scope and estimate.</li><li>Create, set up, and walk through it.</li></ol></aside></div></div></section><section class="section tint"><div class="wrap"><div class="section-head"><div>'+eyebrow('Practical support for small businesses')+'<h2>Look the part. Get set up.<br>Move forward.</h2></div></div><div class="grid2">'
for ic,t,d,items in [('pen','Logo & brand work','Give your business a recognizable look that carries across the places customers see you.',['Logo concepts and refinements','Coordinated colors and visual style','Business cards, flyers, and promotional graphics','Artwork prepared for agreed print and digital uses']),('ad','Advertising setup','Get help turning your offer into clear advertising and setting up the pieces behind it.',['Advertising account and campaign setup','Ad graphics and message development','Audience, budget, and placement planning','A walkthrough of how to manage your setup']),('rocket','Startup consulting','Turn a long list of “I need to figure that out” into a practical launch plan.',['Clarifying your offer and customer experience','Prioritizing your launch tasks','Choosing useful tools and workflows','Coordinating branding, web, and advertising needs']),('web','Web & everyday business tech','Make it easier for customers to find you and for you to get work done.',['Website setup and refresh projects','Business email and connected devices','Forms and simple workflow setup','Computer, printer, and network support'])]:business+=f'<article class="service-card">{icon(ic)}<h2>{t}</h2><p>{d}</p>{checks(items)}</article>'
business+='</div><div class="notice"><strong>Built around your project.</strong> Work is billed at $50/hour, with a free consultation and an estimate for larger projects. We’ll discuss the scope, deliverables, and any advertising spend, printing, software, or equipment costs before you decide.</div></div></section>'+with_business_cta_photo(cta('What are you working on?','A new business, a new look, or a better way to get things done—let’s talk.'))
document('business.html','Logo, Branding, Advertising & Startup Help','Logo and brand design, advertising setup, website help, and practical startup consulting for Eastern Iowa small businesses.',business)

rates=with_rates_illustration(pagehero('Rates & FAQ','Straightforward help.<br>Straightforward pricing.','$50 an hour, with a free consultation to get started and an estimate for larger projects.'))+'<section class="section"><div class="wrap"><div class="price-layout"><article class="price-card featured">'+eyebrow('Tech help & business support')+'<h2>Pay for the help you need.</h2><div class="price">$50<span> / hour</span></div><p>Personal help with your technology or business project. No subscription required.</p>'+checks(['Free initial consultation','Work directly with Josh','Schedule a visit or discuss your project'])+btn('Start with a free consultation','contact.html','light')+'</article><article class="price-card"><h2>Something a little bigger?</h2><p>Branding, advertising setup, a website refresh, or a project with several moving pieces? Let’s talk through it first.</p>'+checks(['Tell me your goals and what you already have','We’ll identify the work and deliverables','Receive an estimate before moving forward','Discuss equipment, software, printing, or ad costs'])+'<p class="small">Your estimate will clarify the project scope and expected cost so you can decide on the next step.</p>'+link('Tell me about your project','contact.html')+'</article></div></div></section><section class="section tint"><div class="wrap"><div class="faq">'+eyebrow('Good questions')+'<h2>Before we get started.</h2>'
faqs=[('Is the consultation really free?','Yes. The initial conversation is free. Tell Josh what’s going on or what you’re planning, and he’ll help identify the next step. Hands-on work is billed at $50/hour.'),('What areas do you serve?','Josh is based in Muscatine and serves the Iowa City and Quad Cities areas. Share your location when you reach out so availability and any travel arrangements can be discussed.'),('Can you help if I’m not good with technology?','Absolutely. Ask the questions you need to ask. The goal is to get things working and help you feel comfortable using them.'),('How do estimates for larger projects work?','Start with a free consultation. Josh will discuss the scope, deliverables, and estimated work with you before you decide to proceed.'),('Are equipment and advertising costs included?','The $50/hour rate is for Josh’s work. Any needed equipment, paid software, printing, or advertising budget will be discussed separately for your project.'),('Can I get help with a new business?','Yes. Services include logo and brand work, advertising setup, website projects, and practical guidance on the tools and tasks involved in getting started.'),('How do I book an appointment?','Text or call 563-261-0200, or prepare an email request on the Contact page. An appointment is arranged directly with Josh; submitting a request does not reserve a time.'),('Do you offer a monthly subscription?','No subscription is needed. Book the help you need at $50/hour, or ask for an estimate for a larger project.')]
for q,a in faqs:rates+=f'<details><summary>{q}</summary><p>{a}</p></details>'
rates+='</div></div></section>'+with_rates_cta_photo(cta('Start with a conversation.','No need to know the technical name for the problem. Just tell me what’s happening.'))
document('rates.html','Rates & Frequently Asked Questions','Tech support and business project help at $50/hour. Free initial consultation and estimates for larger projects. No subscription required.',rates)

kits=with_kits_illustration(pagehero('Digital kits','A little know-how.<br>A lot more confidence.','Plain-English guides and practical checklists you can work through at your own pace. Buy once, download, and get started.'))+'<section class="section"><div class="wrap">'
for name,price,img,desc,items,url in [('Home Network Lockdown Kit','9','home-network-lockdown-kit-cover.png','Take a closer look at your home Wi-Fi and connected devices, with a practical guide to improving your setup.',['19-page plain-English guide','Connected-device inventory','Monthly checklist','Instant digital download'],'home-network-lockdown-kit'),('Small-Business Cyber Hygiene Kit','19','smb-cyber-hygiene-kit-cover.png','Build clearer security habits for your small business with staff-ready resources and useful routines.',['19-page guide','Employee access inventory','Monthly checklist and staff card','Instant digital download'],'smb-cyber-hygiene-kit')]:
 kits+=f'<article class="product"><div class="product-art"><img src="images/{img}" alt="{name} cover" loading="lazy"></div><div class="product-content">{eyebrow("Guides & checklists")}<h2>{name}</h2><div class="product-price">${price}<span>one-time purchase</span></div><p>{desc}</p>{checks(items)}<a class="btn" href="https://joshthetechtamer.gumroad.com/l/{url}" target="_blank" rel="noopener noreferrer">View kit on Gumroad <span aria-hidden="true">↗</span></a><p class="small" style="margin-top:15px;margin-bottom:0">Purchase and download through Gumroad.</p></div></article>'
kits+='<div class="notice"><strong>Prefer a helping hand?</strong> These are self-guided resources. For help with your specific devices or business setup, <a href="contact.html"><u>contact Josh</u></a> for a free consultation.</div></div></section>'+with_help_photo(cta('Rather work through it together?','Local, personal tech help is just a call or text away.'))
document('digital-kits.html','Digital Guides & Checklists','Explore The Tech Tamer’s Home Network Lockdown Kit and Small-Business Cyber Hygiene Kit. Plain-English guides and instant downloads.',kits)

about=pagehero('About Josh','Your local tech guy.<br>Minus the tech-speak.','I’m Josh Sargent—the person behind The Tech Tamer. I help people and small businesses across Eastern Iowa get more comfortable with their technology.')+'<section class="section"><div class="wrap story"><div class="portrait"><img src="assets/josh.jpg" width="600" height="600" alt="Josh Sargent, owner of The Tech Tamer"></div><div>'+eyebrow('Howdy there!')+'<h2>When your tech won’t cooperate,<br>I’m the guy you call.</h2><p>I’ve been helping people work through technology problems since I was a kid in the ’90s. What started as helping family and friends grew into The Tech Tamer: practical, personal help for the things you use every day.</p><p>I’m no plumber. When a pipe leaks, I call someone who knows what they’re doing. Technology is my version of that—I’m here to help when a device won’t cooperate or you don’t know where to start.</p><p>Sometimes that means getting a printer connected. Sometimes it means setting up a TV, making a phone less confusing, or helping a small business bring its branding and technology together.</p><p>Whatever the project, you’ll work directly with me. I’ll explain the plan in plain English and help you understand what comes next.</p><div class="credential"><strong>Electronics Engineering Technology</strong><span>Bachelor’s degree · Hamilton Tech, Davenport</span></div><div class="credential"><strong>Network Engineering</strong><span>Diploma · Muscatine Community College, specializing in Cisco systems</span></div><div class="credential"><strong>Rooted in Eastern Iowa</strong><span>Based in Muscatine · Serving Iowa City and the Quad Cities</span></div>'+btn('Let’s talk','contact.html')+'</div></div></section>'+cta('You don’t have to figure it out alone.','Tell me what you’re trying to do. We’ll start there.')
document('about.html','Meet Josh Sargent','Meet Josh Sargent, The Tech Tamer. Friendly, experienced technology help and small-business support based in Muscatine, Iowa.',about)

contact=pagehero('Contact','Let’s tame your next<br>tech headache.','Tell me what’s happening—or what you’d like to build. We’ll start with a free consultation and figure out the next step.')+'<section class="section"><div class="wrap contact-grid"><div>'+eyebrow('Talk directly with Josh')+'''<div class="contact-option"><h2>Text or call</h2><a href="tel:+15632610200">563-261-0200</a><p>Text is an easy way to describe what you need.</p><div class="actions">'''+btn('Text Josh','sms:+15632610200')+btn('Call Josh','tel:+15632610200','secondary')+'''</div></div><div class="contact-option"><h2>Email</h2><a href="mailto:joshthetechtamer@gmail.com" style="font-size:17px">joshthetechtamer@gmail.com</a></div><div class="contact-option"><h2>Service area</h2><p>Based in Muscatine, Iowa.<br>Serving Iowa City and the Quad Cities.</p></div><div class="contact-option"><h2>Availability</h2><p>Sun–Tue & Thu–Sat: 8 AM–8 PM<br>Wednesday: appointment setting only.</p><p>Contact Josh to arrange a visit.</p></div></div><div class="contact-form"><h2>Tell me what you have in mind.</h2><p>This prepares a message in your email app. Review it and press Send there to get in touch.</p><form id="request-form"><div class="form-row"><div><label for="name">Your name *</label><input id="name" name="name" required autocomplete="name" maxlength="100"></div><div><label for="contact">Phone or email *</label><input id="contact" name="contact" required maxlength="150" autocomplete="email"></div></div><label for="service">What can I help with?</label><select id="service" name="service"><option>Tech help at home</option><option>Logo & brand work</option><option>Advertising setup</option><option>Startup consulting</option><option>Website & business tech</option><option>Something else</option></select><label for="location">City or service location</label><input id="location" name="location" autocomplete="address-level2" maxlength="150" placeholder="For example, Muscatine"><label for="issue">A little about your request *</label><textarea id="issue" name="issue" required maxlength="4000" placeholder="What’s happening, or what would you like help creating?"></textarea><p class="small">Please leave out passwords, payment details, and other sensitive information.</p><button class="btn" type="submit">Prepare email request ↗</button><p class="status" id="form-status" role="status" aria-live="polite">No appointment is booked until you and Josh confirm a time.</p></form></div></div></section>'''
document('contact.html','Contact Josh for a Free Consultation','Text or call Josh at 563-261-0200 for a free consultation about tech support, branding, advertising setup, or a business project.',contact)
document('404.html','Page Not Found','Find tech help, digital kits, and business services from The Tech Tamer.','<section class="notfound"><h1>That page wandered off.</h1><p>Let’s get you back to the right place.</p>'+btn('Back to home','index.html')+'</section>')
(ROOT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#23335c"/><path d="M18 15h28l-3 29H21z" fill="#fff"/><path d="M18 35h28v9H18z" fill="#00a3ed"/><path d="M12 44h40v6H12z" fill="#fff"/></svg>')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+BASE+'/'+('' if f=='index.html' else f)+'</loc></url>' for f in ['index.html','services.html','business.html','digital-kits.html','rates.html','about.html','contact.html'])+'</urlset>')
print('Built 7 pages and a 404 page.')
